# Generated by Django 3.2.13 on 2023-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_autor_auxiliar_avaliador_avaliarprojeto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliarprojeto',
            old_name='paracer',
            new_name='parecer',
        ),
        migrations.RenameField(
            model_name='premio',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='premio',
            name='cronograma',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
