# Generated by Django 4.1.7 on 2023-04-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_enviarprojeto_dataenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviarprojeto',
            name='dataEnvio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='premio',
            name='autor',
        ),
        migrations.AddField(
            model_name='premio',
            name='autor',
            field=models.ManyToManyField(to='catalog.autor'),
        ),
    ]
